"""Package de gestion des artefacts — schema, chemins, stores."""

from .integrity import (
    artifact_integrity_table,
    canonical_artifact_completeness,
    recompute_metrics_from_predictions,
    verifier_integrite_artefacts_modele,
)
from .io import (
    charger_predictions,
    charger_predictions_modele,
    charger_probabilites,
    charger_probabilites_modele,
    charger_resultats_grid_search,
    sauvegarder_figure,
    sauvegarder_figure_globale,
    sauvegarder_predictions,
    sauvegarder_probabilites_oof,
    sauvegarder_resultats_grid_search,
)
from .metrics_store import (
    charger_mesures,
    charger_tableau_mesures,
    charger_tableau_mesures_valides,
    sauvegarder_mesures,
)
from .paths import (
    GlobalArtifactPaths,
    ModelArtifactPaths,
    global_paths,
    model_paths,
)
from .schema import (
    METRICS_SCHEMA_VERSION,
    FigureBundleResult,
    FigureRequest,
    StudyRunResult,
    TuningRunResult,
    UntunedVariantResult,
)
from .validation import (
    REQUIRED_METRIC_KEYS,
    STAGE_MAP,
    MetricsArtifactValidationError,
    derive_selection_protocol,
    derive_stage,
    filtrer_legacy,
    normaliser_mesures_pour_schema,
    normaliser_stades,
    valider_artefacts_mesures,
)

__all__ = [
    "GlobalArtifactPaths",
    "METRICS_SCHEMA_VERSION",
    "MetricsArtifactValidationError",
    "ModelArtifactPaths",
    "FigureBundleResult",
    "FigureRequest",
    "STAGE_MAP",
    "StudyRunResult",
    "TuningRunResult",
    "UntunedVariantResult",
    "artifact_integrity_table",
    "canonical_artifact_completeness",
    "charger_mesures",
    "charger_predictions",
    "charger_predictions_modele",
    "charger_probabilites",
    "charger_probabilites_modele",
    "charger_resultats_grid_search",
    "charger_tableau_mesures",
    "charger_tableau_mesures_valides",
    "derive_selection_protocol",
    "derive_stage",
    "filtrer_legacy",
    "global_paths",
    "model_paths",
    "normaliser_mesures_pour_schema",
    "normaliser_stades",
    "recompute_metrics_from_predictions",
    "REQUIRED_METRIC_KEYS",
    "sauvegarder_figure",
    "sauvegarder_figure_globale",
    "sauvegarder_mesures",
    "sauvegarder_predictions",
    "sauvegarder_probabilites_oof",
    "sauvegarder_resultats_grid_search",
    "verifier_integrite_artefacts_modele",
    "valider_artefacts_mesures",
]
